version: v1.0.0
server:
  port: 80
spring:
  application:
    name: datahub-fs-client
  main:
    banner-mode: 'off'
#  thymeleaf
  thymeleaf:
    enabled: true
    enable-spring-el-compiler: false
    cache: false
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    check-template: true
    check-template-location: true
    reactive:
      max-chunk-size: 0
      
# RPC
rpc:
  client:
    connect:
      server:
        port: 8899
        fs-service-port: 8877

# logging
logging:
  file: logs/${spring.application.name}.log
  level:
    root: info
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
    level: '%5p'